module.exports = [
  {
    lessonId: "L1_M1_L1",
    title: "Structure of Phonics",
    file_path: "lessons/basic/module-1/L1_M1_L1.json",
    keywords: [
      "phonics",
      "phonic",
      "pronunciation",
      "sounds",
      "phonemes",
      "graphemes",
      "digraphs",
      "diphthongs",
      "r-controlled",
      "synthetic phonics",
      "analytic phonics",
      "analogy phonics",
      "embedded phonics",
      "onset-rime phonics",
      "consonant sounds",
      "plosives",
      "fricatives",
      "affricates",
      "nasals",
      "vowel digraphs",
      "gliding vowel",
      "double vowel sound",
      "consonant",
      "vowel",
      "silent e",
      "sound patterns",
    ],
  },
  {
    lessonId: "L1_M1_L2",
    title: "Word Stress",
    file_path: "lessons/basic/module-1/L1_M1_L2.json",
    keywords: [
      "word stress",
      "stress",
      "syllable",
      "stressed syllable",
      "primary stress",
      "secondary stress",
      "unstressed syllable",
    ],
  },
  {
    lessonId: "L1_M1_L3",
    title: "Syllables",
    file_path: "lessons/basic/module-1/L1_M1_L3.json",
    keywords: [
      "syllables",
      "counting syllables",
      "syllable division",
      "open syllables",
      "closed syllables",
      "vowel team syllables",
      "vowel-consonant-e",
      "magic e",
      "prefixes",
      "suffixes",
      "word parts",
    ],
  },
  {
    lessonId: "L1_M2_L1",
    title: "School & Classroom Objects",
    file_path: "lessons/basic/module-2/L1_M2_L1.json",
    keywords: [
      "vocabulary",
      "school",
      "classroom",
      "objects",
      "writing tools",
      "drawing tools",
      "reading surfaces",
      "writing surfaces",
      "classroom furniture",
      "board",
      "cleaning tools",
      "measuring tools",
      "carrying essentials",
      "learning places",
      "play spots",
      "recreation spots",
      "school administration",
      "learning guides",
      "school helpers",
      "students",
      "staff"
    ],
  },
  {
    lessonId: "L1_M2_L2",
    title: "People at Home and Village",
    file_path: "lessons/basic/module-2/L1_M2_L2.json",
    keywords: [
      "family",
      "village",
      "people",
      "home",
      "family members",
      "immediate family",
      "extended family",
      "community helpers",
      "village leaders",
      "religious leaders",
      "sarpanch",
      "neighbor",
      "describing people",
      "friendly",
      "relationships",
    ],
  },
  {
    lessonId: "L1_M2_L3",
    title: "Numbers, Colors, Days, and Months",
    file_path: "lessons/basic/module-2/L1_M2_L3.json",
    keywords: [
      "numbers",
      "counting",
      "colors",
      "time",
    ],
  },
  {
    lessonId: "L1_M2_L4",
    title: "Food, Animals, and Clothes",
    file_path: "lessons/basic/module-2/L1_M2_L4.json",
    keywords: [
      "food",
      "animals",
      "clothes",
      "daily life",
      "farm animals",
      "wild animals",
      "vegetables",
      "describing food",
      "domestic animals",
      "traditional dress",
      "footwear",
      "seasonal clothes",
      "winter",
      "monsoon",
    ],
  },
  {
    lessonId: "L1_M2_L5",
    title: "Musical Instruments and Professions",
    file_path: "lessons/basic/module-2/L1_M2_L5.json",
    keywords: [
      "flashcard",
      "games",
      "memory",
      "music",
      "instruments",
      "profession"
    ],
  },
  {
    lessonId: "L1_M3_L1",
    title: "Synonyms",
    file_path: "lessons/basic/module-3/L1_M3_L1.json",
    keywords: [
      "synonym",
      "similar meaning"
    ],
  },
  {
    lessonId: "L1_M3_L2",
    title: "Antonyms",
    file_path: "lessons/basic/module-3/L1_M3_L2.json",
    keywords: [
      "antonyms",
      "opposites",
      "contrast",
      "opposite meanings"
    ],
  },
  {
    lessonId: "L1_M3_L3",
    title: "Degree of Comparision",
    file_path: "lessons/basic/module-3/L1_M3_L3.json",
    keywords: [
      "intermediate",
      "grammar expansion",
      "degrees of comparison",
      "adjectives",
      "positive degree",
      "comparative degree",
      "superlative degree",
      "comparison",
      "regular adjectives",
      "irregular adjectives",
      "base form",
      "quality",
      "highest degree",
      "forming degrees",
      "irregular comparisons",
      "double comparative",
      "double superlative",
      "syllable counting",
      "comparing things",
    ],
  },
  {
    lessonId: "L1_M3_L4",
    title: "Rhyming Words",
    file_path: "lessons/basic/module-3/L1_M3_L4.json",
    keywords: [
      "rhyming words",
      "rhymes",
      "creating rhymes",
      "musical",
      "rhyming games",
      "two-line poems",
      "rhyming dictionary"
    ],
  },
  {
    lessonId: "L1_M3_L5",
    title: "Homophones and Homographs",
    file_path: "lessons/basic/module-3/L1_M3_L5.json",
    keywords: [
      "homophones",
      "homographs",
      "homonyms",
      "same sound",
      "different meanings",
      "different spellings",
      "same spelling",
      "different pronunciations",
      "same sound and spelling",
    ],
  },
  {
    lessonId: "L1_M3_L6",
    title: "Verb Forms",
    file_path: "lessons/basic/module-3/L1_M3_L6.json",
    keywords: [
      "verbs",
      "verb forms",
      "base form",
      "past simple",
      "past participle",
      "V1",
      "V2",
      "V3",
      "regular verbs",
      "irregular verbs",
      "tenses",
      "simple present",
      "simple past",
      "simple future",
      "present perfect",
      "past perfect",
      "passive voice",
      "conjugation",
      "verb patterns",
      "memorization",
    ],
  },
  {
    lessonId: "L1_M4_L1",
    title: "Nouns: Naming Words Around Us",
    file_path: "lessons/basic/module-4/L1_M4_L1.json",
    keywords: [
      "nouns",
      "naming words",
    ],
  },
  {
    lessonId: "L1_M4_L2",
    title: "Pronouns (I, you, he, she, etc.)",
    file_path: "lessons/basic/module-4/L1_M4_L2.json",
    keywords: [
      "pronouns",
      "replace nouns",
      "personal pronouns",
      "subject pronouns",
      "object pronouns",
      "possessive pronouns",
      "ownership",
      "reflexive pronouns",
      "intensive pronouns",
      "demonstrative pronouns",
      "interrogative pronouns",
      "relative pronouns",
      "indefinite pronouns",
      "reciprocal pronouns",
    ],
  },
  {
    lessonId: "L1_M4_L3",
    title: "Articles (a, an, the)",
    file_path: "lessons/basic/module-4/L1_M4_L3.json",
    keywords: [
      "articles",
      "a",
      "an",
      "the",
      "indefinite articles",
      "definite article",
    ],
  },
  {
    lessonId: "L1_M4_L4",
    title: "Verbs (action words)",
    file_path: "lessons/basic/module-4/L1_M4_L4.json",
    keywords: [
      "grammar",
      "verbs",
      "action words",
      "states of being",
      "identify verbs",
      "present form",
      "past form",
      "future form",
      "sentence structure",
      "types of verbs",
      "action verbs",
      "physical action",
      "mental action",
      "helping verbs",
      "auxiliary verbs",
      "main verbs",
      "tense",
      "be",
      "have",
      "has",
      "had",
      "linking verbs",
      "transitive verbs",
      "intransitive verbs",
      "regular verbs",
      "irregular verbs",
      "modal verbs",
    ],
  },
  {
    lessonId: "L1_M4_L5",
    title: "Subject and Predicate",
    file_path: "lessons/basic/module-4/L1_M4_L5.json",
    keywords: [
      "subject",
      "predicate",
      "sentence parts",
      "complete sense",
      "who or what",
      "what they do",
      "identify subject",
      "identify predicate",
      "what about the subject",
      "action word",
      "simple predicate",
      "compound predicate",
      "WHO",
      "WHAT",
      "WHAT HAPPENS",
      "WHAT IT IS",
    ],
  },
  {
    lessonId: "L1_M4_L6",
    title: "Sentence Structure (S+V+O)",
    file_path: "lessons/basic/module-4/L1_M4_L6.json",
    keywords: [
      "sentence structure",
      "proper sentences",
      "clear sentences",
      "meaningful sentences",
      "who or what does it",
      "action word",
      "what is the action",
      "adverbs",
    ],
  },
  {
    lessonId: "L1_M4_L7",
    title: "Compound Words",
    file_path: "lessons/basic/module-4/L1_M4_L7.json",
    keywords: [
      "joining words",
      "closed compound words",
      "hyphenated compound words"
    ],
  },
  {
    lessonId: "L1_M4_L8",
    title: "Genders",
    file_path: "lessons/basic/module-4/L1_M4_L8.json",
    keywords: [
      "genders",
      "masculine",
      "feminine",
      "female",
      "girl",
      "woman",
      "common gender",
      "neuter gender",
      "no specific gender",
      "gender pairs",
      "similar meanings",
    ],
  },
  {
    lessonId: "L1_M5_L1",
    title: "Introducing Yourself",
    file_path: "lessons/basic/module-5/L1_M5_L1.json",
    keywords: [
      "introduce"
    ]
  },
  {
    lessonId: "L1_M5_L2",
    title: "Greetings & Daily Phrases",
    file_path: "lessons/basic/module-5/L1_M5_L2.json",
    keywords: [
      "greetings",
      "daily phrases",
      "polite words",
      "good morning",
      "good afternoon",
      "good evening",
      "formal language",
      "informal language",
      "daily conversation",
    ],
  },
  {
    lessonId: "L1_M5_L3",
    title: "Listening to Instructions",
    file_path: "lessons/basic/module-5/L1_M5_L3.json",
    keywords: [
      "listening to instructions",
      "listening",
      "commands",
    ],
  },
  {
    lessonId: "L1_M6_L1",
    title: "In the Classroom",
    file_path: "lessons/basic/module-6/L1_M6_L1.json",
    keywords: [
      "classroom",
      "school",
      "talking at school",
      "teacher",
      "friends",
      "asking permission",
      "politely",
    ],
  },
  {
    lessonId: "L1_M6_L2",
    title: "At the Market",
    file_path: "lessons/basic/module-6/L1_M6_L2.json",
    keywords: [
      "market",
      "buying",
      "selling",
    ],
  },
  {
    lessonId: "L1_M6_L3",
    title: "At Home",
    file_path: "lessons/basic/module-6/L1_M6_L3.json",
    keywords: [
      "home",
      "daily life",
      "family talk",
    ],
  },
  {
    lessonId: "L1_M6_L4",
    title: "Celebrations and Festivals",
    file_path: "lessons/basic/module-6/L1_M6_L4.json",
    keywords: [
      "celebrations",
      "festivals",
      "village festivals",
      "culture",
      "special events",
      "special occasion"
    ],
  },
  {
    lessonId: "L1_M6_L5",
    title: "Daily Routine Conversations",
    file_path: "lessons/basic/module-6/L1_M6_L5.json",
    keywords: [
      "daily routine",
      "conversations",
      "morning routine",
      "afternoon routine",
      "evening routine",
      "night routine",
    ],
  },
  {
    lessonId: "L2_M1_L1",
    title: "Tenses and Types of Tenses",
    file_path: "lessons/intermediate/module-1/L2_M1_L1.json",
    keywords: [
      "tenses",
      "types of tenses",
      "past",
      "present",
      "future",
      "simple",
      "continuous",
      "progressive",
      "perfect",
      "perfect continuous",
      "present tense",
      "past tense",
      "future tense",
      "simple present tense",
      "habits",
      "routines",
      "general truths",
      "facts",
      "base form",
      "s",
      "es",
      "daily habit",
      "universal fact",
      "regular situation",
      "fixed schedule",
      "subject",
      "v1",
      "does",
      "do",
      "present continuous tense",
      "happening right now",
      "temporary actions",
      "definite future plans",
      "verb to be",
      "am",
      "is",
      "are",
      "ing form",
      "ongoing activity",
      "fixed plan",
      "present participle",
      "v1-ing",
      "present perfect tense",
      "unspecified time",
      "relevance to the present",
      "started in the past",
      "continues to the present",
      "have",
      "has",
      "past participle",
      "v3",
      "life experience",
      "recent past action",
      "present perfect continuous tense",
      "duration",
      "recently finished",
      "result in the present",
      "in progress",
      "emphasizes duration",
      "past tense",
      "simple past tense",
      "completed actions",
      "specific point in the past",
      "regular verbs",
      "ed",
      "irregular verbs",
      "v2",
      "past continuous tense",
      "ongoing action in the past",
      "interrupted action",
      "two actions happening at the same time",
      "was",
      "were",
      "parallel actions",
      "past perfect tense",
      "completed before another action in the past",
      "past of the past",
      "sequence of events",
      "past perfect continuous tense",
      "duration of an action in progress",
      "how long",
      "had been",
      "cause of a past state",
      "future tense",
      "simple future tense",
      "will",
      "be going to",
      "predictions",
      "spontaneous decisions",
      "promises",
      "planned future action",
      "pre-decided plan",
      "intention",
      "future continuous tense",
      "ongoing action at a specific time in the future",
      "will be",
      "longer ongoing future action",
      "interrupted by a shorter one",
      "future perfect tense",
      "completed before a specific time in the future",
      "will have",
      "future perfect continuous tense",
      "duration of an action in progress up to a certain point in the future",
      "will have been",
      "future milestone",
    ],
  },
  {
    lessonId: "L2_M1_L2",
    title: "Simple Present Tense: Talking about Daily Activities",
    file_path: "lessons/intermediate/module-1/L2_M1_L2.json",
    keywords: [
      "present tense",
      "simple present tense",
      "daily life",
      "habits",
      "facts",
      "daily routines",
      "positive sentences",
      "affirmative",
      "negative sentences",
      "question sentences",
      "interrogative",
      "verb",
      "verbs",
      "base form",
      "-s",
      "-es",
      "spelling rules",
      "do not",
      "don't",
      "does not",
      "doesn't",
      "do...?",
      "does...?",
      "scheduled events",
      "future meaning",
      "instructions",
      "directions",
      "common mistakes",
      "subject-verb agreement",
      "present continuous tense",
      "present progressive",
      "-ing",
      "temporary situations",
      "planned future events",
      "am",
      "is",
      "are",
      "stative verbs",
      "present perfect tense",
      "past participle",
      "have",
      "has",
      "unspecified time",
      "results",
      "for",
      "since",
      "present perfect continuous tense",
      "present perfect progressive",
      "duration",
    ],
  },
  {
    lessonId: "L2_M1_L3",
    title: "Simple Past Tense: Talking About Things That Happened",
    file_path: "lessons/intermediate/module-1/L2_M1_L3.json",
    keywords: [
      "past tense",
      "sentence formation",
      "simple past tense",
      "completed actions",
      "finished events",
      "regular verbs",
      "-ed",
      "spelling rules",
      "irregular verbs",
      "verb forms",
      "positive sentences",
      "affirmative",
      "negative sentences",
      "question sentences",
      "interrogative",
      "did not",
      "didn't",
      "base form",
      "did...?",
      "specific time",
      "series of actions",
      "past habits",
      "common mistakes",
      "past continuous tense",
      "past progressive",
      "ongoing past actions",
      "was",
      "were",
      "-ing",
      "present participle",
      "interrupted actions",
      "parallel actions",
      "past perfect tense",
      "earlier past",
      "sequence of events",
      "auxiliary verb",
      "had",
      "past participle",
      "had not",
      "hadn't",
      "past perfect continuous tense",
      "past perfect progressive",
      "duration before past event",
      "had been",
    ],
  },
  {
    lessonId: "L2_M1_L4",
    title: "Simple Future Tense: Talking About Things That Will Happen",
    file_path: "lessons/intermediate/module-1/L2_M1_L4.json",
    keywords: [
      "future tense",
      "simple future tense",
      "will",
      "be going to",
      "future continuous",
      "future perfect",
      "future perfect continuous",
      "predictions",
      "spontaneous decisions",
      "promises",
      "offers",
      "plans",
      "intentions",
      "present evidence",
      "commands",
      "base form",
      "verb-ing",
      "past participle",
      "v1",
      "v3",
      "grammar",
      "sentence structure",
      "positive sentences",
      "negative sentences",
      "question sentences",
      "formation",
      "usage",
      "common mistakes",
      "am",
      "is",
      "are",
      "won't",
      "isn't",
      "aren't",
    ],
  },
  {
    lessonId: "L2_M1_L5",
    title: "Making Questions and Negatives",
    file_path: "lessons/intermediate/module-1/L2_M1_L5.json",
    keywords: [
      "questions",
      "negatives",
      "question words",
      "yes/no questions",
      "be verbs",
      "sentence patterns",
      "question tags",
      "responses",
    ],
  },
  {
    lessonId: "L2_M2_L1",
    title: "Adverbs and Types of Adverbs",
    file_path: "lessons/intermediate/module-2/L2_M2_L1.json",
    keywords: [
      "adverbs",
      "verbs",
      "adjectives",
      "adverb formation",
      "-ly",
      "irregular adverbs",
      "comparative adverbs",
      "superlative adverbs",
    ],
  },
  {
    lessonId: "L2_M2_L2",
    title: "Adjectives and Types of Adjectives",
    file_path: "lessons/intermediate/module-2/L2_M2_L2.json",
    keywords: [
      "adjectives",
      "describing",
      "descriptive adjectives",
      "quantitative adjectives",
      "demonstrative adjectives",
      "possessive adjectives",
      "interrogative adjectives",
      "distributive adjectives",
      "comparative adjectives",
      "superlative adjectives",
      "comparing three or more",
    ],
  },
  {
    lessonId: "L2_M2_L3",
    title: "Prepositions (in, on, under, etc.)",
    file_path: "lessons/intermediate/module-2/L2_M2_L3.json",
    keywords: [
      "prepositions",
    ],
  },
  {
    lessonId: "L2_M2_L4",
    title: "Conjunctions (and, but, because)",
    file_path: "lessons/intermediate/module-2/L2_M2_L4.json",
    keywords: [
      "conjunctions",
      "joining words",
      "connecting sentences",
      "coordinating conjunctions",
      "subordinating conjunctions",
      "sentence structure",
      "sentence combining",
      "adding information",
      "comma rule",
    ],
  },
  {
    lessonId: "L2_M2_L5",
    title: "Prefix, Suffix, and Roots",
    file_path: "lessons/intermediate/module-2/L2_M2_L5.json",
    keywords: [
      "prefixes",
      "suffixes",
      "root words",
      "word parts",
    ],
  },
  {
    lessonId: "L2_M2_L6",
    title: "Subject-Verb Agreement",
    file_path: "lessons/intermediate/module-2/L2_M2_L6.json",

    keywords: [
      "subject-verb agreement",
      "singular subject",
      "plural subject",
      "singular verb",
      "plural verb",
      "basic agreement rules",
      "compound subjects",
      "indefinite pronouns",
      "sentence structure",
      "correct sentences",
      "English grammar",
    ],
  },
  {
    lessonId: "L2_M2_L7",
    title: "Sentence Types (statement, question, command)",
    file_path: "lessons/intermediate/module-2/L2_M2_L7.json",
    keywords: [
      "sentence types",
      "statement",
      "exclamation",
      "declarative",
      "interrogative",
      "imperative",
      "exclamatory",
      "punctuation",
      "full stop",
      "period",
      "question mark",
      "exclamation mark",
    ],
  },
  {
    lessonId: "L2_M3_L1",
    title: "Village Announcements (Audio Comprehension)",
    file_path: "lessons/intermediate/module-3/L2_M3_L1.json",
    keywords: [
      "village announcements",
      "audio comprehension",
      "announcements",
      "information extraction",
      "listening skills",
      "loudspeakers",
      "messages",
      "community",
      "stay informed",
      "school holidays",
      "village meetings",
      "health camps",
      "danger warnings",
      "heavy rain",
      "floods",
      "listening carefully",
      "effective listening",
      "listening strategies",
      "keywords",
      "main idea",
      "note-taking",
      "note-taking techniques",
    ],
  },
  {
    lessonId: "L2_M3_L2",
    title: "Weather Reports (Listening Task)",
    file_path: "lessons/intermediate/module-3/L2_M3_L2.json",
    keywords: [
      "weather",
      "reports",
      "forecasts",
      "temperature",
      "wind",
      "rainfall",
      "prediction",
      "dust storm",
      "cloudy",
      "degrees Celsius",
      "heavy rain",
      "precipitation",
      "lightning",
      "thundershowers",
      "prolonged rain",
      "cloudburst",
      "cyclone",
      "monsoon",
      "drought",
      "humidity",
      "atmospheric pressure",
      "barometric pressure",
    ],
  },
  {
    lessonId: "L2_M3_L3",
    title: "Folk Tales (Reading)",
    file_path: "lessons/intermediate/module-3/L2_M3_L3.json",
    keywords: [
      "folk tales",
      "stories",
      "characters",
      "cultural stories",
      "cultural values",
      "moral lessons",
      "traditional knowledge",
      "storytelling",
    ],
  },
  {
    lessonId: "L2_M3_L4",
    title: "News Headlines (Skimming & Scanning)",
    file_path: "lessons/intermediate/module-3/L2_M3_L4.json",
    keywords: [
      "news",
      "headlines",
      "skimming",
      "scanning",
      "strategies",
      "extract",
      "information",
      "main idea",
      "brief",
      "time-saving",
      "summary",
      "general understanding",
      "fast reading",
      "main topic",
      "sub-headline",
    ],
  },
  {
    lessonId: "L2_M3_L5",
    title: "Main Idea and Story Details",
    file_path: "lessons/intermediate/module-3/L2_M3_L5.json",
    keywords: [
      "main idea",
      "story details",
      "summarize",
      "summarizing",
      "summary",
      "text",
      "central point",
      "big picture",
      "topic sentence",
      "supporting details",
      "key information",
      "article",
      "news report",
      "announcement",
      "conversation",
      "folk tale",
      "description",
      "advice",
      "problem",
      "daily activity",
      "natural phenomenon",
      "character's journey",
      "shared problem",
      "general observation",
      "repeated words",
      "author",
      "facts",
      "strategies",
      "writing",
      "highlight",
      "underline",
      "notes",
      "draft",
      "review",
      "refine",
      "transition words",
      "rephrase",
      "length",
      "main characters",
      "actions",
      "opinions",
      "factual",
    ],
  },
  {
    lessonId: "L2_M4_L1",
    title: "Sentence Sequencing",
    file_path: "lessons/intermediate/module-4/L2_M4_L1.json",
    keywords: [
      "paragraph writing",
      "letter writing",
      "sentence sequencing",
      "logical order",
      "proper order",
      "logical sequence",
      "transition words",
      "transition phrases",
    ],
  },
  {
    lessonId: "L2_M4_L2",
    title: 'Paragraph on "My Village"',
    file_path: "lessons/intermediate/module-4/L2_M4_L2.json",
    keywords: [
      "my village",
      "descriptive writing",
      "organize ideas",
      "logical order",
      "paragraph structure",
      "descriptive writing techniques",
    ],
  },
  {
    lessonId: "L2_M4_L3",
    title: "Diary Entry Writing",
    file_path: "lessons/intermediate/module-4/L2_M4_L3.json",
    keywords: [
      "diary entry",
      "diary writing",
      "personal diary",
      "thoughts",
      "feelings",
      "diary format",
    ],
  },
  {
    lessonId: "L2_M4_L4",
    title: "Letter to a Friend",
    file_path: "lessons/intermediate/module-4/L2_M4_L4.json",
    keywords: [
      "letter writing",
      "informal letter",
      "letter to a friend",
      "friendly letter",
      "informal letter format",
      "friendship",
      "personal news",
      "sender's address",
      "expressing feelings",
    ],
  },
  {
    lessonId: "L2_M4_L5",
    title: "Informal Message Writing",
    file_path: "lessons/intermediate/module-4/L2_M4_L5.json",
    keywords: [
      "informal message",
      "message writing",
      "concise messages",
      "message format",
      "invitation messages",
      "information messages",
      "request messages",
      "apology messages",
    ],
  },
  {
    lessonId: "L2_M5_L1",
    title: "Buying Vegetables",
    file_path: "lessons/intermediate/module-5/L2_M5_L1.json",
    keywords: [
      "Intermediate",
      "Real Life English",
      "Role Play English",
      "Buying Vegetables",
      "market conversation skills",
      "bargaining language",
      "money transactions",
      "vegetable names",
      "quantities",
      "Market Basics",
      "Common Market Words",
      "Sample Market Conversation",
      "Role-Play Activity",
    ],
  },
  {
    lessonId: "L2_M5_L2",
    title: "Asking for Directions",
    file_path: "lessons/intermediate/module-5/L2_M5_L2.json",
    keywords: [
      "Asking for Directions",
      "request directions",
      "give directions",
      "directional instructions",
      "prepositions of place",
      "prepositions of movement",
      "conversation skills",
      "Basic Direction Words",
      "Key Direction Words",
    ],
  },
  {
    lessonId: "L2_M5_L3",
    title: "Visiting a Doctor",
    file_path: "lessons/intermediate/module-5/L2_M5_L3.json",
    keywords: [
      "Visiting a Doctor",
      "health problems",
      "medical instructions",
      "health conversations",
      "Common Health Problems",
      "body parts",
      "Common Illnesses",
      "Fever",
      "Cough",
      "Cold",
      "Headache",
      "Stomach ache",
      "Body pain",
      "Weakness",
      "Vomiting",
      "Diarrhea",
      "Sore throat",
      "Dizziness",
      "Cut",
      "Bruise",
      "Rash",
      "Swelling",
      "Itching",
      "Nausea",
      "Constipation",
      "Difficulty breathing",
      "Loss of appetite",
      "Talking to the Doctor",
      "Making an Appointment",
      "Greeting",
      "clinic staff",
      "Good morning Doctor",
      "Good afternoon Doctor",
      "Excuse me",
      "waiting room",
      "emergency",
      "doctor available",
      "Describing Your Problem",
      "Injury",
      "Skin problem",
      "Sleep problem",
      "Burning sensation",
      "Earache",
      "Eye irritation",
      "Numbness",
      "Understanding Doctor's Instructions",
      "Medicine",
      "Treatment Vocabulary",
      "Tablet",
      "Pill",
      "Syrup",
      "Injection",
      "Dose",
      "Rest",
      "Diet",
      "Exercise",
      "Bandage",
      "Cream",
      "Ointment",
      "Prescription",
      "Consultation",
      "diet restriction",
      "activity restriction",
      "side effects",
      "Rest period",
      "Medicine storage",
    ],
  },
  {
    lessonId: "L2_M5_L4",
    title: "Planning a School Event",
    file_path: "lessons/intermediate/module-5/L2_M5_L4.json",
    keywords: [
      "planning a school event",
      "event planning",
      "group activities",
    ],
  },
  {
    lessonId: "L2_M5_L5",
    title: "Role-Play and Group Tasks",
    file_path: "lessons/intermediate/module-5/L2_M5_L5.json",
    keywords: [
      "role play english",
      "role-play",
      "group tasks",
      "apply skills",
      "real-life scenarios",
      "confident speaking",
      "group work",
    ],
  },
  {
    lessonId: "L3_M1_L1",
    title: "Direct and Indirect Speech",
    file_path: "lessons/advanced/module-1/L3_M1_L1.json",
    keywords: [
      "direct speech",
      "indirect speech",
      "reported speech",
      "conversion rules",
      "quotation marks",
      "reporting verb",
    ],
  },
  {
    lessonId: "L3_M1_L2",
    title: "Active and Passive Voice",
    file_path: "lessons/advanced/module-1/L3_M1_L2.json",
    keywords: [
      "active voice",
      "passive voice",
      "active to passive conversion",
      "effective passive voice usage",
      "action",
      "doer",
      "receiver",
      "helping verb",
      "be verb",
      "past participle",
      "v3",
      "by phrase",
    ],
  },
  {
    lessonId: "L3_M1_L3",
    title: "Figurative Speeches",
    file_path: "lessons/advanced/module-1/L3_M1_L3.json",
    keywords: [
      "literary devices",
      "figurative language",
      "idioms",
      "metaphor",
      "personification",
      "simile",
      "hyperbole",
      "alliteration",
      "onomatopoeia",
    ],
  },
  {
    lessonId: "L3_M1_L4",
    title: "Basic Words and Advanced Words",
    file_path: "lessons/advanced/module-1/L3_M1_L4.json",
    keywords: [
      "basic words",
      "advanced words",
      "english words",
      "fluent",
      "descriptive",
      "impactful",
      "precise",
      "ask",
      "inquire",
      "tell",
      "inform",
      "get",
      "obtain",
      "acquire",
      "use",
      "utilize",
      "start",
      "commence",
      "end",
      "conclude",
      "help",
      "assist",
      "good",
      "excellent",
      "superb",
      "bad",
      "awful",
      "terrible",
      "happy",
      "delighted",
      "ecstatic",
      "sad",
      "sorrowful",
      "melancholy",
      "big",
      "enormous",
      "gigantic",
      "small",
      "tiny",
      "minuscule",
      "important",
      "crucial",
      "essential",
      "interesting",
      "fascinating",
      "captivating",
      "scared",
      "terrified",
      "petrified",
      "tired",
      "exhausted",
      "fatigued",
      "smart",
      "intelligent",
      "brilliant",
      "brave",
      "courageous",
      "valiant",
      "think",
      "ponder",
      "contemplate",
      "show",
      "demonstrate",
      "illustrate",
      "rich",
      "wealthy",
      "affluent",
      "poor",
      "impoverished",
      "destitute",
      "old",
      "ancient",
      "elderly",
      "angry",
      "furious",
      "enraged",
      "beautiful",
      "exquisite",
      "stunning",
      "fast",
      "swift",
      "rapid",
      "slow",
      "leisurely",
      "sluggish",
      "sure",
      "certain",
      "clear",
      "transparent",
      "apparent",
      "wrong",
      "erroneous",
      "empty",
      "vacant",
      "context",
      "writing",
      "speaking",
      "tips",
    ],
  },
  {
    lessonId: "L3_M2_L1",
    title: "Writing a Folk Tale",
    file_path: "lessons/advanced/module-2/L3_M2_L1.json",
    keywords: [
      "folk tale",
      "folk tales",
      "storytelling",
      "structure",
      "moral lessons",
      "repetitive patterns",
      "cultural significance", 
    ],
  },
  {
    lessonId: "L3_M2_L2",
    title: "Essay Writing (My Dream, My Hero)",
    file_path: "lessons/advanced/module-2/L3_M2_L2.json",
    keywords: [
      "creative writing",
      "academic writing",
      "essay writing",
      "personal essays",
      "organizing thoughts",
      "ideas",
      "hook",
      "thesis",
      "main idea",
    ],
  },
  {
    lessonId: "L3_M2_L3",
    title: "Compare and Contrast Writing",
    file_path: "lessons/advanced/module-2/L3_M2_L3.json",
    keywords: [
      "writing skills",
      "compare and contrast",
      "comparing",
      "contrasting",
      "similarities",
      "differences",
      "transition words",
      "block method",
      "subject-by-subject",
      "point-by-point", 
      "structure",
      "analysis",
    ],
  },
  {
    lessonId: "L3_M2_L4",
    title: "Writing Chapter Summaries",
    file_path: "lessons/advanced/module-2/L3_M2_L4.json",
    keywords: [
      "writing skills",
      "chapter summaries",
      "summary",
      "summaries",
      "main ideas",
      "key information",
      "condensing",
      "concise",
      "overview",
      "details",
      "academic",
      "novel",
      "history",
      "science",
      "conclusion statements",
    ],
  },
  {
    lessonId: "L3_M3_L1",
    title: "Describe a Picture or Object",
    file_path: "lessons/advanced/module-3/L3_M3_L1.json",
    keywords: [
      "describe",
      "description",
      "picture",
      "object",
      "observation",
      "details",
      "characteristics",
      "size",
      "shape",
      "color",
      "texture",
      "position",
      "senses",
      "sight",
      "touch",
      "sound",
      "smell",
      "taste",
      "spatial",
      "location",
      "left",
      "right",
      "top",
      "bottom",
      "near",
      "far",
      "center",
      "edges",
      "importance",
      "similes",
      "metaphors",
      "vivid",
      "precise",
    ],
  },
  {
    lessonId: "L3_M3_L2",
    title: "Prepare & Deliver a Speech",
    file_path: "lessons/advanced/module-3/L3_M3_L2.json",
    keywords: [
      "speech",
      "deliver",
      "conclusion",
      "main points",
      "organization",
      "research",
      "content",
      "writing",
      "outlining",
      "outline",
      "techniques",
      "feedback",
      "communication",
      "skills",
      "informative",
      "persuasive",
      "pauses",
      "confidence",
      "breathing",
      "visualization",
      "self-talk",
      "tips",
    ],
  },
  {
    lessonId: "L3_M3_L3",
    title: "Group Discussion Practice",
    file_path: "lessons/advanced/module-3/L3_M3_L3.json",
    keywords: [
      "group discussion",
      "discussion",
      "practice",
      "skills",
      "participation",
      "listening",
      "active listening",
      "responding",
      "ideas",
      "presenting",
      "speaking",
      "leadership",
      "collaboration",
      "communication",
      "critical thinking",
      "consensus",
      "viewpoints",
      "evidence",
      "initiating",
      "disagreements",
      "constructively",
      "group roles",
      "time management",
      "redirecting",
      "summarizing",
      "conflict resolution",
      "tips",
    ],
  },
  {
    lessonId: "L3_M3_L4",
    title: "Debate on Common Issues",
    file_path: "lessons/advanced/module-3/L3_M3_L4.json",
    keywords: [
      "debate",
      "debating",
      "arguments",
      "evidence",
      "reasoning",
      "counter-arguments",
      "viewpoints",
      "listening",
      "active listening",
      "responding",
      "issues",
    ],
  },
  {
    lessonId: "L3_M4_L1",
    title: "Mock Interviews",
    file_path: "lessons/advanced/module-4/L3_M4_L1.json",
    keywords: [
      "mock interviews",
      "interviews",
      "job interview",
      "professional",
      "face-to-face",
      "behavioral",
      "technical",
      "informational",
      "personal",
      "achievements",
      "teamwork",
    ],
  },
  {
    lessonId: "L3_M4_L2",
    title: "Planning a Community Event",
    file_path: "lessons/advanced/module-4/L3_M4_L2.json",
    keywords: [
      "community"
    ],
  },
  {
    lessonId: "L3_M4_L3",
    title: "Role-Play (Bank Visit, Travel Help)",
    file_path: "lessons/advanced/module-4/L3_M4_L3.json",
    keywords: [
      "role-play",
      "bank visit",
      "travel help",
      "communication",
      "scenarios",
      "customer service",
      "polite expressions",
      "professional",
      "bank account",
      "loan application",
      "travel agency",
      "airport help",
      "transportation",
      "customer language",
      "service provider language",
      "practice tips",
      "challenging scenarios",
      "real-life situations",
      "problem-solving",
      "hotel booking"
    ],
  },
  {
    lessonId: "L3_M4_L4",
    title: "Expressing Opinions in English",
    file_path: "lessons/advanced/module-4/L3_M4_L4.json",
    keywords: [
      "speaking",
      "opinions",
      "expressing",
      "agreeing",
      "disagreeing",
      "formal",
      "informal",
      "reasons",
      "support",
      "conversation",
      "communication",
      "phrases",
      "vocabulary",
      "skills",
      "polite",
      "confident",
      "respectful",
      "beliefs",
      "feelings",
      "thoughts",
      "perspective",
    ],
  },
];