module.exports = [
  {
    lessonId: "L1_M1_L1",
    title: "Structure of Phonics",
    file_path: "lessons/basic/module-1/L1_M1_L1.json",
    keywords: [
      "phonics",
      "sounds",
      "letters",
      "pronunciation",
      "alphabet",
      "vowels",
      "consonants",
    ],
  },
  {
    lessonId: "L1_M1_L2",
    title: "Word Stress",
    file_path: "lessons/basic/module-1/L1_M1_L2.json",
    keywords: [
      "word stress",
      "emphasis",
      "syllable stress",
      "pronunciation",
      "accent",
      "rhythm",
    ],
  },
  {
    lessonId: "L1_M1_L3",
    title: "Syllables",
    file_path: "lessons/basic/module-1/L1_M1_L3.json",
    keywords: [
      "syllables",
      "word parts",
      "breaking words",
      "clapping",
      "counting",
      "pronunciation",
    ],
  },
  {
    lessonId: "L1_M2_L1",
    title: "School & Classroom Objects",
    file_path: "lessons/basic/module-2/L1_M2_L1.json",
    keywords: [
      "school",
      "classroom",
      "objects",
      "desk",
      "chair",
      "board",
      "book",
      "pen",
      "pencil",
    ],
  },
  {
    lessonId: "L1_M2_L2",
    title: "People at Home and Village",
    file_path: "lessons/basic/module-2/L1_M2_L2.json",
    keywords: [
      "family",
      "people",
      "home",
      "village",
      "mother",
      "father",
      "brother",
      "sister",
      "neighbor",
    ],
  },
  {
    lessonId: "L1_M2_L3",
    title: "Numbers, Colors, Days, and Months",
    file_path: "lessons/basic/module-2/L1_M2_L3.json",
    keywords: [
      "numbers",
      "colors",
      "days",
      "months",
      "counting",
      "red",
      "blue",
      "Monday",
      "January",
    ],
  },
  {
    lessonId: "L1_M2_L4",
    title: "Food, Animals, and Clothes",
    file_path: "lessons/basic/module-2/L1_M2_L4.json",
    keywords: [
      "food",
      "animals",
      "clothes",
      "rice",
      "cat",
      "dog",
      "shirt",
      "dress",
      "eat",
      "wear",
    ],
  },
  {
    lessonId: "L1_M2_L5",
    title: "Musical Instruments and Professions",
    file_path: "lessons/basic/module-2/L1_M2_L5.json",
    keywords: [
      "music",
      "instruments",
      "professions",
      "jobs",
      "guitar",
      "drum",
      "teacher",
      "doctor",
      "farmer",
    ],
  },
  {
    lessonId: "L1_M3_L1",
    title: "Synonyms",
    file_path: "lessons/basic/module-3/L1_M3_L1.json",
    keywords: [
      "synonyms",
      "same meaning",
      "similar words",
      "big",
      "large",
      "happy",
      "joyful",
    ],
  },
  {
    lessonId: "L1_M3_L2",
    title: "Antonyms",
    file_path: "lessons/basic/module-3/L1_M3_L2.json",
    keywords: [
      "antonyms",
      "opposite",
      "different meaning",
      "hot",
      "cold",
      "big",
      "small",
      "up",
      "down",
    ],
  },
  {
    lessonId: "L1_M3_L3",
    title: "Degree of Comparision",
    file_path: "lessons/basic/module-3/L1_M3_L3.json",
    keywords: [
      "comparison",
      "comparative",
      "superlative",
      "bigger",
      "biggest",
      "more",
      "most",
      "less",
      "least",
    ],
  },
  {
    lessonId: "L1_M3_L4",
    title: "Rhyming Words",
    file_path: "lessons/basic/module-3/L1_M3_L4.json",
    keywords: [
      "rhyming",
      "rhyme",
      "sounds alike",
      "cat",
      "bat",
      "sun",
      "fun",
      "poetry",
    ],
  },
  {
    lessonId: "L1_M3_L5",
    title: "Homophones and Homographs",
    file_path: "lessons/basic/module-3/L1_M3_L5.json",
    keywords: [
      "homophones",
      "homographs",
      "same sound",
      "same spelling",
      "to",
      "two",
      "too",
      "read",
    ],
  },
  {
    lessonId: "L1_M3_L6",
    title: "Verb Forms",
    file_path: "lessons/basic/module-3/L1_M3_L6.json",
    keywords: [
      "verb forms",
      "verbs",
      "go",
      "went",
      "gone",
      "run",
      "ran",
      "present",
      "past",
    ],
  },
  {
    lessonId: "L1_M4_L1",
    title: "Nouns: Naming Words Around Us",
    file_path: "lessons/basic/module-4/L1_M4_L1.json",
    keywords: [
      "noun",
      "nouns",
      "naming word",
      "thing",
      "object",
      "person",
      "place",
    ],
  },
  {
    lessonId: "L1_M4_L2",
    title: "Pronouns (I, you, he, she, etc.)",
    file_path: "lessons/basic/module-4/L1_M4_L2.json",
    keywords: [
      "pronoun",
      "I",
      "you",
      "he",
      "she",
      "it",
      "we",
      "they",
      "replacing noun",
    ],
  },
  {
    lessonId: "L1_M4_L3",
    title: "Articles (a, an, the)",
    file_path: "lessons/basic/module-4/L1_M4_L3.json",
    keywords: [
      "articles",
      "a",
      "an",
      "the",
      "indefinite",
      "definite",
      "before noun",
    ],
  },
  {
    lessonId: "L1_M4_L4",
    title: "Verbs (action words)",
    file_path: "lessons/basic/module-4/L1_M4_L4.json",
    keywords: [
      "verb",
      "verbs",
      "action word",
      "doing word",
      "run",
      "eat",
      "sleep",
    ],
  },
  {
    lessonId: "L1_M4_L5",
    title: "Subject and Predicate",
    file_path: "lessons/basic/module-4/L1_M4_L5.json",
    keywords: [
      "subject",
      "predicate",
      "sentence parts",
      "SVO",
      "who",
      "what does",
    ],
  },
  {
    lessonId: "L1_M4_L6",
    title: "Sentence Structure (S+V+O)",
    file_path: "lessons/basic/module-4/L1_M4_L6.json",
    keywords: [
      "sentence structure",
      "SVO",
      "subject",
      "verb",
      "object",
      "word order",
      "grammar",
    ],
  },
  {
    lessonId: "L1_M4_L7",
    title: "Compound Words",
    file_path: "lessons/basic/module-4/L1_M4_L7.json",
    keywords: [
      "compound words",
      "two words",
      "combined",
      "sunflower",
      "classroom",
      "football",
    ],
  },
  {
    lessonId: "L1_M4_L8",
    title: "Genders",
    file_path: "lessons/basic/module-4/L1_M4_L8.json",
    keywords: [
      "gender",
      "masculine",
      "feminine",
      "neuter",
      "boy",
      "girl",
      "man",
      "woman",
    ],
  },
  {
    lessonId: "L1_M5_L1",
    title: "Introducing Yourself",
    file_path: "lessons/basic/module-5/L1_M5_L1.json",
    keywords: [
      "introduction",
      "name",
      "age",
      "where from",
      "my name is",
      "I am",
      "hello",
    ],
  },
  {
    lessonId: "L1_M5_L2",
    title: "Greetings & Daily Phrases",
    file_path: "lessons/basic/module-5/L1_M5_L2.json",
    keywords: [
      "greetings",
      "hello",
      "good morning",
      "goodbye",
      "please",
      "thank you",
      "daily phrases",
    ],
  },
  {
    lessonId: "L1_M5_L3",
    title: "Listening to Instructions",
    file_path: "lessons/basic/module-5/L1_M5_L3.json",
    keywords: [
      "listening",
      "instructions",
      "follow",
      "commands",
      "sit down",
      "stand up",
      "open",
      "close",
    ],
  },
  {
    lessonId: "L1_M6_L1",
    title: "In the Classroom",
    file_path: "lessons/basic/module-6/L1_M6_L1.json",
    keywords: [
      "classroom",
      "school",
      "teacher",
      "student",
      "lesson",
      "study",
      "learn",
      "homework",
    ],
  },
  {
    lessonId: "L1_M6_L2",
    title: "At the Market",
    file_path: "lessons/basic/module-6/L1_M6_L2.json",
    keywords: [
      "market",
      "buy",
      "sell",
      "vegetables",
      "fruits",
      "money",
      "price",
      "shopping",
    ],
  },
  {
    lessonId: "L1_M6_L3",
    title: "At Home",
    file_path: "lessons/basic/module-6/L1_M6_L3.json",
    keywords: [
      "home",
      "family",
      "house",
      "room",
      "kitchen",
      "bedroom",
      "living",
      "daily activities",
    ],
  },
  {
    lessonId: "L1_M6_L4",
    title: "Celebrations and Festivals",
    file_path: "lessons/basic/module-6/L1_M6_L4.json",
    keywords: [
      "celebrations",
      "festivals",
      "birthday",
      "Diwali",
      "Christmas",
      "party",
      "joy",
      "happiness",
    ],
  },
  {
    lessonId: "L1_M6_L5",
    title: "Daily Routine Conversations",
    file_path: "lessons/basic/module-6/L1_M6_L5.json",
    keywords: [
      "daily routine",
      "morning",
      "evening",
      "breakfast",
      "lunch",
      "dinner",
      "wake up",
      "sleep",
    ],
  },
  {
    lessonId: "L2_M1_L1",
    title: "Tenses and Types of Tenses",
    file_path: "lessons/intermediate/module-1/L2_M1_L1.json",
    keywords: [
      "tense",
      "tenses",
      "present",
      "past",
      "future",
      "time",
      "action tense",
    ],
  },
  {
    lessonId: "L2_M1_L2",
    title: "Simple Present Tense: Talking about Daily Activities",
    file_path: "lessons/intermediate/module-1/L2_M1_L2.json",
    keywords: [
      "simple present",
      "daily activities",
      "habits",
      "routine",
      "always",
      "usually",
      "never",
    ],
  },
  {
    lessonId: "L2_M1_L3",
    title: "Simple Past Tense: Talking About Things That Happened",
    file_path: "lessons/intermediate/module-1/L2_M1_L3.json",
    keywords: [
      "simple past",
      "happened",
      "yesterday",
      "last week",
      "ago",
      "was",
      "were",
      "did",
    ],
  },
  {
    lessonId: "L2_M1_L4",
    title: "Simple Future Tense: Talking About Things That Will Happen",
    file_path: "lessons/intermediate/module-1/L2_M1_L4.json",
    keywords: [
      "simple future",
      "will happen",
      "tomorrow",
      "next week",
      "will",
      "going to",
      "shall",
    ],
  },
  {
    lessonId: "L2_M1_L5",
    title: "Making Questions and Negatives",
    file_path: "lessons/intermediate/module-1/L2_M1_L5.json",
    keywords: [
      "questions",
      "negatives",
      "do",
      "does",
      "did",
      "not",
      "wh questions",
      "yes no questions",
    ],
  },
  {
    lessonId: "L2_M2_L1",
    title: "Adverbs and Types of Adverbs",
    file_path: "lessons/intermediate/module-2/L2_M2_L1.json",
    keywords: [
      "adverb",
      "adverbs",
      "how",
      "when",
      "where",
      "manner",
      "frequency",
    ],
  },
  {
    lessonId: "L2_M2_L2",
    title: "Adjectives and Types of Adjectives",
    file_path: "lessons/intermediate/module-2/L2_M2_L2.json",
    keywords: [
      "adjective",
      "adjectives",
      "describing word",
      "quality",
      "beautiful",
      "tall",
      "color",
    ],
  },
  {
    lessonId: "L2_M2_L3",
    title: "Prepositions (in, on, under, etc.)",
    file_path: "lessons/intermediate/module-2/L2_M2_L3.json",
    keywords: [
      "prepositions",
      "in",
      "on",
      "under",
      "above",
      "between",
      "position",
      "location",
    ],
  },
  {
    lessonId: "L2_M2_L4",
    title: "Conjunctions (and, but, because)",
    file_path: "lessons/intermediate/module-2/L2_M2_L4.json",
    keywords: [
      "conjunctions",
      "and",
      "but",
      "because",
      "so",
      "or",
      "joining words",
      "connecting",
    ],
  },
  {
    lessonId: "L2_M2_L5",
    title: "Prefix, Suffix, and Roots",
    file_path: "lessons/intermediate/module-2/L2_M2_L5.json",
    keywords: [
      "prefix",
      "suffix",
      "roots",
      "word parts",
      "un-",
      "-ing",
      "-ed",
      "meaning",
    ],
  },
  {
    lessonId: "L2_M2_L6",
    title: "Subject-Verb Agreement",
    file_path: "lessons/intermediate/module-2/L2_M2_L6.json",
    keywords: [
      "subject verb agreement",
      "singular",
      "plural",
      "is",
      "are",
      "matching",
      "grammar",
    ],
  },
  {
    lessonId: "L2_M2_L7",
    title: "Sentence Types (statement, question, command)",
    file_path: "lessons/intermediate/module-2/L2_M2_L7.json",
    keywords: [
      "sentence types",
      "statement",
      "question",
      "command",
      "exclamation",
      "declarative",
      "imperative",
    ],
  },
  {
    lessonId: "L2_M3_L1",
    title: "Village Announcements (Audio Comprehension)",
    file_path: "lessons/intermediate/module-3/L2_M3_L1.json",
    keywords: [
      "listening",
      "audio",
      "village",
      "announcements",
      "comprehension",
      "understanding",
      "hearing",
    ],
  },
  {
    lessonId: "L2_M3_L2",
    title: "Weather Reports (Listening Task)",
    file_path: "lessons/intermediate/module-3/L2_M3_L2.json",
    keywords: [
      "weather",
      "reports",
      "listening",
      "sunny",
      "rainy",
      "cloudy",
      "temperature",
      "forecast",
    ],
  },
  {
    lessonId: "L2_M3_L3",
    title: "Folk Tales (Reading)",
    file_path: "lessons/intermediate/module-3/L2_M3_L3.json",
    keywords: [
      "folk tales",
      "reading",
      "stories",
      "traditional",
      "moral",
      "characters",
      "plot",
    ],
  },
  {
    lessonId: "L2_M3_L4",
    title: "News Headlines (Skimming & Scanning)",
    file_path: "lessons/intermediate/module-3/L2_M3_L4.json",
    keywords: [
      "news",
      "headlines",
      "skimming",
      "scanning",
      "reading skills",
      "quick reading",
      "main idea",
    ],
  },
  {
    lessonId: "L2_M3_L5",
    title: "Main Idea and Story Details",
    file_path: "lessons/intermediate/module-3/L2_M3_L5.json",
    keywords: [
      "main idea",
      "story details",
      "comprehension",
      "understanding",
      "theme",
      "supporting details",
    ],
  },
  {
    lessonId: "L2_M4_L1",
    title: "Sentence Sequencing",
    file_path: "lessons/intermediate/module-4/L2_M4_L1.json",
    keywords: [
      "sentence sequencing",
      "order",
      "arrange",
      "logical",
      "first",
      "then",
      "finally",
    ],
  },
  {
    lessonId: "L2_M4_L2",
    title: 'Paragraph on "My Village"',
    file_path: "lessons/intermediate/module-4/L2_M4_L2.json",
    keywords: [
      "paragraph",
      "my village",
      "writing",
      "description",
      "community",
      "home",
      "place",
    ],
  },
  {
    lessonId: "L2_M4_L3",
    title: "Diary Entry Writing",
    file_path: "lessons/intermediate/module-4/L2_M4_L3.json",
    keywords: [
      "diary",
      "entry",
      "writing",
      "personal",
      "daily",
      "thoughts",
      "feelings",
      "experiences",
    ],
  },
  {
    lessonId: "L2_M4_L4",
    title: "Letter to a Friend",
    file_path: "lessons/intermediate/module-4/L2_M4_L4.json",
    keywords: [
      "letter",
      "friend",
      "informal",
      "writing",
      "greeting",
      "closing",
      "communication",
    ],
  },
  {
    lessonId: "L2_M4_L5",
    title: "Informal Message Writing",
    file_path: "lessons/intermediate/module-4/L2_M4_L5.json",
    keywords: [
      "informal message",
      "writing",
      "short",
      "casual",
      "note",
      "quick",
      "communication",
    ],
  },
  {
    lessonId: "L2_M5_L1",
    title: "Buying Vegetables",
    file_path: "lessons/intermediate/module-5/L2_M5_L1.json",
    keywords: [
      "buying",
      "vegetables",
      "market",
      "conversation",
      "price",
      "bargaining",
      "shopping",
    ],
  },
  {
    lessonId: "L2_M5_L2",
    title: "Asking for Directions",
    file_path: "lessons/intermediate/module-5/L2_M5_L2.json",
    keywords: [
      "directions",
      "asking",
      "where",
      "how to go",
      "left",
      "right",
      "straight",
      "near",
    ],
  },
  {
    lessonId: "L2_M5_L3",
    title: "Visiting a Doctor",
    file_path: "lessons/intermediate/module-5/L2_M5_L3.json",
    keywords: [
      "doctor",
      "visit",
      "health",
      "symptoms",
      "medicine",
      "appointment",
      "medical",
    ],
  },
  {
    lessonId: "L2_M5_L4",
    title: "Planning a School Event",
    file_path: "lessons/intermediate/module-5/L2_M5_L4.json",
    keywords: [
      "planning",
      "school event",
      "organization",
      "preparation",
      "teamwork",
      "coordination",
    ],
  },
  {
    lessonId: "L2_M5_L5",
    title: "Role-Play and Group Tasks",
    file_path: "lessons/intermediate/module-5/L2_M5_L5.json",
    keywords: [
      "role play",
      "group tasks",
      "teamwork",
      "acting",
      "simulation",
      "practice",
      "interaction",
    ],
  },
  {
    lessonId: "L3_M1_L1",
    title: "Direct and Indirect Speech",
    file_path: "lessons/advanced/module-1/L3_M1_L1.json",
    keywords: [
      "direct speech",
      "indirect speech",
      "reported speech",
      "quotation",
      "say",
      "tell",
    ],
  },
  {
    lessonId: "L3_M1_L2",
    title: "Active and Passive Voice",
    file_path: "lessons/advanced/module-1/L3_M1_L2.json",
    keywords: [
      "active voice",
      "passive voice",
      "subject does",
      "object affected",
      "by",
    ],
  },
  {
    lessonId: "L3_M1_L3",
    title: "Figurative Speeches",
    file_path: "lessons/advanced/module-1/L3_M1_L3.json",
    keywords: [
      "figurative speech",
      "metaphor",
      "simile",
      "idioms",
      "expressions",
      "creative language",
    ],
  },
  {
    lessonId: "L3_M1_L4",
    title: "Basic Words and Advanced Words",
    file_path: "lessons/advanced/module-1/L3_M1_L4.json",
    keywords: [
      "vocabulary",
      "basic words",
      "advanced words",
      "word choice",
      "sophisticated",
      "improvement",
    ],
  },
  {
    lessonId: "L3_M2_L1",
    title: "Writing a Folk Tale",
    file_path: "lessons/advanced/module-2/L3_M2_L1.json",
    keywords: [
      "folk tale",
      "creative writing",
      "story",
      "characters",
      "plot",
      "moral",
      "traditional",
    ],
  },
  {
    lessonId: "L3_M2_L2",
    title: "Essay Writing (My Dream, My Hero)",
    file_path: "lessons/advanced/module-2/L3_M2_L2.json",
    keywords: [
      "essay",
      "writing",
      "my dream",
      "my hero",
      "structured",
      "introduction",
      "conclusion",
    ],
  },
  {
    lessonId: "L3_M2_L3",
    title: "Compare and Contrast Writing",
    file_path: "lessons/advanced/module-2/L3_M2_L3.json",
    keywords: [
      "compare",
      "contrast",
      "similarities",
      "differences",
      "analysis",
      "comparison",
      "writing",
    ],
  },
  {
    lessonId: "L3_M2_L4",
    title: "Writing Chapter Summaries",
    file_path: "lessons/advanced/module-2/L3_M2_L4.json",
    keywords: [
      "chapter summary",
      "summarizing",
      "main points",
      "condensing",
      "key ideas",
      "brief",
    ],
  },
  {
    lessonId: "L3_M3_L1",
    title: "Describe a Picture or Object",
    file_path: "lessons/advanced/module-3/L3_M3_L1.json",
    keywords: [
      "description",
      "picture",
      "object",
      "speaking",
      "details",
      "observation",
      "visual",
    ],
  },
  {
    lessonId: "L3_M3_L2",
    title: "Prepare & Deliver a Speech",
    file_path: "lessons/advanced/module-3/L3_M3_L2.json",
    keywords: [
      "speech",
      "preparation",
      "delivery",
      "public speaking",
      "presentation",
      "audience",
      "confidence",
    ],
  },
  {
    lessonId: "L3_M3_L3",
    title: "Group Discussion Practice",
    file_path: "lessons/advanced/module-3/L3_M3_L3.json",
    keywords: [
      "group discussion",
      "practice",
      "participation",
      "opinions",
      "listening",
      "speaking",
      "ideas",
    ],
  },
  {
    lessonId: "L3_M3_L4",
    title: "Debate on Common Issues",
    file_path: "lessons/advanced/module-3/L3_M3_L4.json",
    keywords: [
      "debate",
      "arguments",
      "issues",
      "for and against",
      "reasoning",
      "persuasion",
      "discussion",
    ],
  },
  {
    lessonId: "L3_M4_L1",
    title: "Mock Interviews",
    file_path: "lessons/advanced/module-4/L3_M4_L1.json",
    keywords: [
      "mock interview",
      "questions",
      "answers",
      "job",
      "preparation",
      "confidence",
      "professional",
    ],
  },
  {
    lessonId: "L3_M4_L2",
    title: "Planning a Community Event",
    file_path: "lessons/advanced/module-4/L3_M4_L2.json",
    keywords: [
      "community event",
      "planning",
      "organization",
      "leadership",
      "coordination",
      "teamwork",
    ],
  },
  {
    lessonId: "L3_M4_L3",
    title: "Role-Play (Bank Visit, Travel Help)",
    file_path: "lessons/advanced/module-4/L3_M4_L3.json",
    keywords: [
      "role play",
      "conversation",
      "dialogue",
      "bank",
      "travel",
      "help",
      "scenario",
    ],
  },
  {
    lessonId: "L3_M4_L4",
    title: "Expressing Opinions in English",
    file_path: "lessons/advanced/module-4/L3_M4_L4.json",
    keywords: [
      "opinions",
      "expressing",
      "thoughts",
      "views",
      "I think",
      "in my opinion",
      "perspective",
    ],
  },
];
